import {
  initializeNotifications,
  onNotificationEvent,
  terminateNotifications,
} from 'desktop-notifications'
import { BrowserWindow, Notification } from 'electron'
import * as path from 'path'
import { findToastActivatorClsid } from '../lib/find-toast-activator-clsid'
import { DesktopAliveEvent } from '../lib/stores/alive-store'
import * as ipcWebContents from './ipc-webcontents'

let windowsToastActivatorClsid: string | undefined = undefined
const linuxNotifications = new Map<string, Notification>()
const MaxLinuxNotifications = 200

let notificationEventCallback:
  | ((event: 'click', id: string, userInfo: DesktopAliveEvent) => void)
  | null = null

export function initializeDesktopNotifications() {
  if (__LINUX__) {
    // Linux notifications use Electron's libnotify-backed Notification API.
    return
  }

  if (__DARWIN__) {
    initializeNotifications({})
    return
  }

  if (windowsToastActivatorClsid !== undefined) {
    return
  }

  windowsToastActivatorClsid = findToastActivatorClsid()

  if (windowsToastActivatorClsid === undefined) {
    log.error(
      'Toast activator CLSID not found in any of the shortcuts. Falling back to known CLSIDs.'
    )

    // This is generated by Squirrel.Windows here:
    // https://github.com/Squirrel/Squirrel.Windows/blob/7396fa50ccebf97e28c79ef519c07cb9eee121be/src/Squirrel/UpdateManager.ApplyReleases.cs#L258
    windowsToastActivatorClsid = '{27D44D0C-A542-5B90-BCDB-AC3126048BA2}'
  }

  log.info(`Using toast activator CLSID ${windowsToastActivatorClsid}`)
  initializeNotifications({ toastActivatorClsid: windowsToastActivatorClsid })
}

export function terminateDesktopNotifications() {
  for (const notification of linuxNotifications.values()) {
    notification.close()
  }
  linuxNotifications.clear()
  terminateNotifications()
}

export function installNotificationCallback(window: BrowserWindow) {
  notificationEventCallback = (event, id, userInfo) => {
    ipcWebContents.send(
      window.webContents,
      'notification-event',
      event,
      id,
      userInfo
    )
  }

  onNotificationEvent<DesktopAliveEvent>(notificationEventCallback)
}

/**
 * Shows a Linux desktop notification and returns an ID that the renderer can
 * associate with its in-memory click callback. Electron uses libnotify on
 * Linux, which supports desktop environments implementing the freedesktop
 * Desktop Notifications specification.
 */
export function showLinuxNotification(
  title: string,
  body: string,
  userInfo?: DesktopAliveEvent
): string | null {
  if (!Notification.isSupported()) {
    return null
  }

  const id = crypto.randomUUID()
  const notification = new Notification({
    title,
    body,
    icon: path.join(__dirname, 'static', 'icon-logo.png'),
    urgency: 'normal',
  })

  // Notification instances must stay referenced for click events to arrive.
  if (linuxNotifications.size >= MaxLinuxNotifications) {
    const oldestID = linuxNotifications.keys().next().value
    if (oldestID !== undefined) {
      linuxNotifications.get(oldestID)?.close()
      linuxNotifications.delete(oldestID)
    }
  }
  linuxNotifications.set(id, notification)

  notification.once('click', () => {
    linuxNotifications.delete(id)
    // The renderer first resolves its in-memory callback by ID. The optional
    // userInfo is only needed as a fallback after an app session change.
    notificationEventCallback?.('click', id, userInfo as DesktopAliveEvent)
  })
  notification.once('close', () => linuxNotifications.delete(id))

  try {
    notification.show()
    return id
  } catch (error) {
    linuxNotifications.delete(id)
    log.error('Unable to show Linux desktop notification', error)
    return null
  }
}
