import * as path from 'path'
import * as cp from 'child_process'
import { rename } from 'fs-extra'
import { getVersion } from '../app/package-info'
import { getDistPath, getDistRoot } from './dist-info'
import { mkdirSync, writeFileSync, rmSync, statSync } from 'fs'

function getArchitecture() {
  const arch = process.env.npm_config_arch || process.arch

  switch (arch) {
    case 'arm64':
      return 'aarch64'
    case 'arm':
      return 'armv7h'
    default:
      return 'x86_64'
  }
}

const distRoot = getDistRoot()

function generatePKGINFO(arch: string, installedSize: number): string {
  const version = getVersion().replace(/[:\-]/g, '.')
  return `# Generated by GitHub Desktop packaging
pkgbase = github-desktop
pkgname = github-desktop
pkgver = ${version}-1
pkgdesc = Simple collaboration from your desktop
url = https://github.com/desktop/desktop
arch = ${arch}
builddate = ${Math.floor(Date.now() / 1000)}
packager = GitHub Desktop Team <github@github.com>
size = ${installedSize}
license = MIT
depend = libcurl-compat
depend = libsecret
depend = gnome-keyring
`
}

function generateBUILDINFO(arch: string): string {
  const version = getVersion().replace(/[:\-]/g, '.')
  const builddate = Math.floor(Date.now() / 1000)
  return `format = 2
pkgname = github-desktop
pkgbase = github-desktop
pkgver = ${version}-1
pkgarch = ${arch}
packager = GitHub Desktop Team <github@github.com>
builddate = ${builddate}
builddir = .
startdir = .
buildtool = github-desktop-packager
`
}

function getInstalledSize(dirPath: string): number {
  let totalSize = 0
  const result = cp.spawnSync('find', [dirPath, '-type', 'f'], { encoding: 'utf-8' })
  if (result.stdout) {
    const files = result.stdout.trim().split('\n').filter(Boolean)
    for (const file of files) {
      try {
        totalSize += statSync(file).size
      } catch {
        // skip files we can't stat
      }
    }
  }
  return totalSize
}

export async function packageArchLinux(): Promise<string> {
  if (process.platform === 'win32') {
    return Promise.reject('Windows is not supported')
  }

  const arch = getArchitecture()
  const version = getVersion().replace(/[:\-]/g, '.')

  const buildDir = path.join(distRoot, `archbuild-${arch}`)
  const pkgDir = path.join(buildDir, 'pkg')

  // Clean and create directories
  rmSync(buildDir, { recursive: true, force: true })
  mkdirSync(pkgDir, { recursive: true })

  // Create directory structure in pkg
  const dirs = [
    `${pkgDir}/opt/github-desktop`,
    `${pkgDir}/usr/bin`,
    `${pkgDir}/usr/share/applications`,
    `${pkgDir}/usr/share/icons/hicolor/512x512/apps`,
    `${pkgDir}/usr/share/icons/hicolor/256x256/apps`,
    `${pkgDir}/usr/share/icons/hicolor/128x128/apps`,
    `${pkgDir}/usr/share/icons/hicolor/64x64/apps`,
    `${pkgDir}/usr/share/icons/hicolor/32x32/apps`,
  ]

  for (const dir of dirs) {
    mkdirSync(dir, { recursive: true })
  }

  // Copy application files
  const cpResult = cp.spawnSync('cp', ['-r', `${getDistPath()}/.`, `${pkgDir}/opt/github-desktop/`], {
    stdio: 'inherit',
  })
  if (cpResult.status !== 0) {
    return Promise.reject(new Error(`Failed to copy application files to ${pkgDir}/opt/github-desktop/`))
  }

  // Copy icons
  const iconSizes = ['32x32', '64x64', '128x128', '256x256', '512x512']
  for (const size of iconSizes) {
    const src = path.join(__dirname, '..', 'app', 'static', 'linux', 'logos', `${size}.png`)
    const dest = path.join(pkgDir, 'usr', 'share', 'icons', 'hicolor', size, 'apps', 'github-desktop.png')
    cp.spawnSync('cp', [src, dest], { stdio: 'inherit' })
  }

  // Create symlink for binary
  const lnResult = cp.spawnSync('ln', ['-sf', '/opt/github-desktop/desktop', `${pkgDir}/usr/bin/github-desktop`], {
    stdio: 'inherit',
  })
  if (lnResult.status !== 0) {
    return Promise.reject(new Error('Failed to create binary symlink'))
  }

  // Create desktop file
  const desktopContent = `[Desktop Entry]
Name=GitHub Desktop
Comment=Git GUI
Exec=/opt/github-desktop/desktop %U
Icon=github-desktop
Type=Application
Categories=GNOME;GTK;Development;RevisionControl;
MimeType=x-scheme-handler/x-github-client;x-scheme-handler/x-github-desktop-auth;
`
  writeFileSync(`${pkgDir}/usr/share/applications/github-desktop.desktop`, desktopContent)

  // Calculate installed size
  const installedSize = getInstalledSize(pkgDir)

  // Create .PKGINFO and .BUILDINFO in pkgDir (same as makepkg)
  writeFileSync(path.join(pkgDir, '.PKGINFO'), generatePKGINFO(arch, installedSize))
  writeFileSync(path.join(pkgDir, '.BUILDINFO'), generateBUILDINFO(arch))

  // Generate .MTREE using bsdtar (same approach as makepkg)
  // Use -printf '%P' to strip the leading './' so paths match what pacman expects
  const mtreeCmd = `cd '${pkgDir}' && find . -mindepth 1 -printf '%P\\0' | LANG=C bsdtar -cnf - --format=mtree --options='!all,use-set,type,uid,gid,mode,time,size,sha256,link' --null --files-from - --exclude .MTREE | gzip -c -f -n > .MTREE`
  const mtreeResult = cp.spawnSync('sh', ['-c', mtreeCmd], { stdio: 'inherit' })
  if (mtreeResult.status !== 0) {
    return Promise.reject(new Error('Failed to generate .MTREE file (is bsdtar/libarchive-tools installed?)'))
  }

  // Create the tar archive using the same approach as makepkg
  const pkgFileName = `github-desktop-${version}-1-${arch}.pkg.tar.zst`
  const pkgPath = path.join(distRoot, pkgFileName)

  const tarCmd = `cd '${pkgDir}' && find . -mindepth 1 -printf '%P\\0' | LANG=C bsdtar --no-fflags --no-read-sparse -cnf - --null --files-from - | zstd -T0 -19 > '${pkgPath}'`
  const tarResult = cp.spawnSync('sh', ['-c', tarCmd], { stdio: 'inherit' })

  if (tarResult.error || tarResult.status !== 0) {
    return Promise.reject(new Error(`Failed to create package archive: ${tarResult.error?.message || `exit code ${tarResult.status}`}`))
  }

  // Rename to our naming convention
  const newFileName = `GitHubDesktop-linux-${arch}-${getVersion()}.pkg.tar.zst`
  const newPath = path.join(distRoot, newFileName)
  await rename(pkgPath, newPath)

  return Promise.resolve(newPath)
}
