import * as path from 'path'
import * as cp from 'child_process'
import { rename } from 'fs-extra'
import { getVersion } from '../app/package-info'
import { getDistPath, getDistRoot } from './dist-info'
import { mkdirSync, writeFileSync, rmSync } from 'fs'

function getArchitecture() {
  const arch = process.env.npm_config_arch || process.arch

  switch (arch) {
    case 'arm64':
      return 'aarch64'
    case 'arm':
      return 'armv7h'
    default:
      return 'x86_64'
  }
}

const distRoot = getDistRoot()

function generatePKGINFO(arch: string): string {
  const version = getVersion().replace(/[:\-]/g, '.')
  return `# Generated by GitHub Desktop packaging
pkgname = github-desktop
pkgver = ${version}-1
pkgdesc = Simple collaboration from your desktop
url = https://github.com/desktop/desktop
arch = ${arch}
builddate = ${Math.floor(Date.now() / 1000)}
packager = GitHub Desktop Team <github@github.com>
size = 0
license = MIT
depends = electron
depends = libcurl-compat
depends = libsecret
depends = gnome-keyring
`
}

export async function packageArchLinux(): Promise<string> {
  if (process.platform === 'win32') {
    return Promise.reject('Windows is not supported')
  }

  const arch = getArchitecture()
  const version = getVersion().replace(/[:\-]/g, '.')

  const buildDir = path.join(distRoot, `archbuild-${arch}`)
  const pkgDir = path.join(buildDir, 'pkg')

  // Clean and create directories
  rmSync(buildDir, { recursive: true, force: true })
  mkdirSync(pkgDir, { recursive: true })

  // Create directory structure in pkg
  const dirs = [
    `${pkgDir}/opt/github-desktop`,
    `${pkgDir}/usr/bin`,
    `${pkgDir}/usr/share/applications`,
    `${pkgDir}/usr/share/icons/hicolor/512x512/apps`,
    `${pkgDir}/usr/share/icons/hicolor/256x256/apps`,
    `${pkgDir}/usr/share/icons/hicolor/128x128/apps`,
    `${pkgDir}/usr/share/icons/hicolor/64x64/apps`,
    `${pkgDir}/usr/share/icons/hicolor/32x32/apps`,
  ]

  for (const dir of dirs) {
    mkdirSync(dir, { recursive: true })
  }

  // Copy application files
  cp.spawnSync('cp', ['-r', `${getDistPath()}/.`, `${pkgDir}/opt/github-desktop/`], {
    stdio: 'inherit',
  })

  // Copy icons
  const iconSizes = ['32x32', '64x64', '128x128', '256x256', '512x512']
  for (const size of iconSizes) {
    const src = path.join(__dirname, '..', 'app', 'static', 'linux', 'logos', `${size}.png`)
    const dest = path.join(pkgDir, 'usr', 'share', 'icons', 'hicolor', size, 'apps', 'github-desktop.png')
    cp.spawnSync('cp', [src, dest], { stdio: 'inherit' })
  }

  // Create symlink for binary
  cp.spawnSync('ln', ['-sf', '/opt/github-desktop/desktop', `${pkgDir}/usr/bin/github-desktop`], {
    stdio: 'inherit',
  })

  // Create desktop file
  const desktopContent = `[Desktop Entry]
Name=GitHub Desktop
Comment=Git GUI
Exec=/opt/github-desktop/desktop %U
Icon=github-desktop
Type=Application
Categories=GNOME;GTK;Development;RevisionControl;
MimeType=x-scheme-handler/x-github-client;x-scheme-handler/x-github-desktop-auth;
`
  writeFileSync(`${pkgDir}/usr/share/applications/github-desktop.desktop`, desktopContent)

  // Create .PKGINFO in buildDir
  writeFileSync(path.join(buildDir, '.PKGINFO'), generatePKGINFO(arch))

  // Create the tar archive
  const pkgFileName = `github-desktop-${version}-1-${arch}.pkg.tar.zst`
  const pkgPath = path.join(distRoot, pkgFileName)

  // Build tar with zstd compression from buildDir
  const tarResult = cp.spawnSync(
    'tar',
    ['--zstd', '-cf', pkgPath, '-C', buildDir, '.PKGINFO', '-C', pkgDir, '.'],
    { stdio: 'inherit' }
  )

  if (tarResult.error) {
    return Promise.reject(tarResult.error)
  }

  // Rename to our naming convention
  const newFileName = `GitHubDesktop-linux-${arch}-${getVersion()}.pkg.tar.zst`
  const newPath = path.join(distRoot, newFileName)
  await rename(pkgPath, newPath)

  return Promise.resolve(newPath)
}
